### ISSUE TITLE
Auto resize textbox isn't scrollable after it hits max size

### ISSUE THREAD

**Issue by zachseidner1** [jonathanjma/happiness-app-frontend#7]
![image](https://github.com/jonathanjma/happiness-app-frontend/assets/58796478/b3647840-99a6-472b-ac68-db4be2cf7ff8)
I cannot scroll down to view the rest of the entry.

**Comment by Alex967CW** [comment]
Yeah, I removed the scrolling functionality because the scrollbar was basically interfering with autoresizing thing. It's still possible to navigate by using the arrow keys

**Comment by zachseidner1** [comment]
I feel like there's gotta be a way to make it scrollable once it hits a max size, having to use the arrow keys to navigate is pretty unintuitive.
